lancache:
  enabled: false
  ipaddrs:
    - 192.168.69.28
upstreams:
  - 192.168.69.18
  - 192.168.69.3

unbound_private_domains:
  - intra.tormakris.dev.
  - tormakristof.eu.
  - ctrl-alt-gg.hu.
  - ctrl-alt.gg.

unbound_domain_insecure:
  - intra.tormakris.dev.
  - tormakristof.eu.
  - ctrl-alt-gg.hu.
  - ctrl-alt.gg.

unbound_authoritative_reverse_zones:
  - 128.168.192.in-addr.arpa.
  - 130.168.192.in-addr.arpa.
  - 132.168.192.in-addr.arpa.
  - 133.168.192.in-addr.arpa.
  - 140.168.192.in-addr.arpa.
  - 141.168.192.in-addr.arpa.
  - 142.168.192.in-addr.arpa.
  - 143.168.192.in-addr.arpa.
  - 144.168.192.in-addr.arpa.
  - 145.168.192.in-addr.arpa.
  - 146.168.192.in-addr.arpa.
  - 147.168.192.in-addr.arpa.
  - 148.168.192.in-addr.arpa.
  - 149.168.192.in-addr.arpa.
  - 150.168.192.in-addr.arpa.
...
