---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        molecule: {}
  tasks:
    - name: Create a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: "{{ item.command | default('sleep 1d') }}"
        privileged: "{{ item.privileged | default(false) }}"
        capabilities: "{{ item.capabilities | default([]) }}"
        security_opts: "{{ item.security_opts | default([]) }}"
        volumes: "{{ item.volumes | default([]) }}"
        tmpfs: "{{ item.tmpfs | default([]) }}"
        exposed_ports: "{{ item.exposed_ports | default([]) }}"
        published_ports: "{{ item.published_ports | default([]) }}"
        env: "{{ item.env | default({}) }}"
        hostname: "{{ item.hostname | default(item.name) }}"
        networks: "{{ item.networks | default([]) }}"
        network_mode: "{{ item.network_mode | default('bridge') }}"
        dns_servers: "{{ item.dns_servers | default([]) }}"
        dns_search_domains: "{{ item.dns_search_domains | default([]) }}"
        restart_policy: "{{ item.restart_policy | default('no') }}"
        memory: "{{ item.memory | default(omit) }}"
        memory_swap: "{{ item.memory_swap | default(omit) }}"
        cpus: "{{ item.cpus | default(omit) }}"
        ulimits: "{{ item.ulimits | default([]) }}"
        sysctls: "{{ item.sysctls | default({}) }}"
        working_dir: "{{ item.working_dir | default(omit) }}"
        user: "{{ item.user | default(omit) }}"
        labels: "{{ item.labels | default({}) }}"
        log_driver: "{{ item.log_driver | default('json-file') }}"
        log_options: "{{ item.log_options | default({}) }}"
        cgroupns_mode: "{{ item.cgroupns_mode | default(omit) }}"
        pre_build_image: "{{ item.pre_build_image | default(true) }}"
        detach: true
        interactive: "{{ item.interactive | default(false) }}"
        tty: "{{ item.tty | default(false) }}"
        stdin_open: "{{ item.stdin_open | default(false) }}"
        auto_remove: "{{ item.auto_remove | default(false) }}"
        read_only: "{{ item.read_only | default(false) }}"
        init: "{{ item.init | default(false) }}"
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Print container creation info
      ansible.builtin.debug:
        msg: |
          Container: {{ item.container.Name }}
          State: {{ item.container.State.Status }}
          Image: {{ item.container.Config.Image }}
          Command: {{ item.container.Config.Cmd }}
          Privileged: {{ item.container.HostConfig.Privileged }}
        verbosity: 1
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Fail if container is not running
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.include_tasks:
        file: tasks/create-fail.yml
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  "{{ item.name }}":
                    ansible_connection: community.docker.docker
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
      run_once: true # noqa: run-once[task]

- name: Validate that inventory was refreshed
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Display uname info
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

    - name: Verify container capabilities
      ansible.builtin.raw: cat /proc/self/status | grep Cap
      register: caps_result
      changed_when: false
      failed_when: false

    - name: Display container capabilities
      ansible.builtin.debug:
        msg: "Container capabilities: {{ caps_result.stdout_lines }}"
        verbosity: 1
...
