---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml
platforms:
  - name: rocky10-integration
    image: quay.io/rockylinux/rockylinux:10
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    exposed_ports:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 123/udp
provisioner:
  name: ansible
  config_options:
    defaults:
      gathering: smart
      fact_caching: memory
  inventory:
    host_vars:
      rocky10-integration:
        ntp_upstreams:
          - type: "server"
            host: "time.cloudflare.com"
            nts: true
        ntp_allow:
          - 127.0.0.1
          - 10.0.0.0/8
        lancache:
          enabled: false
          ipaddrs:
            - 192.168.69.28
        upstreams:
          - 1.1.1.1
          - 9.9.9.9
        interfaces:
          - eth0
        subnets:
          - 192.168.128.0/24
        dns_servers:
          - 192.168.129.53
        ntp_servers:
          - 192.168.129.123
        timedatectl_timezone: 'UTC'
        timedatectl_timeservers: ['pool.ntp.org']
        timedatectl_timeservers_fallback: ['time.nist.gov']
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
...
