---
- name: Prepare
  hosts: all
  become: true
  become_method: su

  tasks:
    - name: Install sudo first
      ansible.builtin.dnf:
        name: sudo
        state: present
      become_method: su

    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: true

    - name: Install basic packages for testing
      ansible.builtin.dnf:
        name:
          - systemd
          - openssh-server
          - bind-utils
        state: present

    - name: Ensure systemd is running # noqa ignore-errors
      ansible.builtin.systemd:
        name: systemd-logind
        state: started
        enabled: true
      ignore_errors: true
...
