---
- name: Restorecon bracket
  ansible.builtin.command: "restorecon -Rv {{ bracket_project_dir }}"
  changed_when: false
  when: ansible_selinux.status == 'enabled'

- name: Restart bracket
  community.docker.docker_compose_v2:
    project_src: "{{ bracket_project_dir }}"
    state: restarted

- name: Restart auditd
  ansible.builtin.command: augenrules --load
  changed_when: false
...
