---
- name: Prepare Rocky 10 machine for Ansible automation
  hosts: "{{ target_host }}"
  become: yes

  vars_prompt:
    - name: "target_host"
      prompt: "Machine to set up"
      private: no
    - name: "username"
      prompt: "User to SSH as (needs ROOT access)"
      private: no
      default: "root"
    - name: "password"
      prompt: "Password of initial user"
      private: yes
    - name: "ansible_username"
      prompt: "Ansible username"
      default: "ansible"


  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    automation_user: "{{ ansible_username }}"
    automation_group: "{{ ansible_username }}"
    automation_home: "/home/{{ ansible_username }}"
    ssh_key_comment: "ansible-automation-key"

  tasks:
    - name: Create ansible group
      ansible.builtin.group:
        name: "{{ automation_group }}"
        state: present

    - name: Create ansible user
      ansible.builtin.user:
        name: "{{ automation_user }}"
        group: "{{ automation_group }}"
        home: "{{ automation_home }}"
        shell: /bin/bash
        create_home: yes
        system: no
        state: present

    - name: Set up SSH directory for ansible user
      ansible.builtin.file:
        path: "{{ automation_home }}/.ssh"
        state: directory
        owner: "{{ automation_user }}"
        group: "{{ automation_group }}"
        mode: '0700'

    - name: Generate SSH key pair for ansible user
      community.crypto.openssh_keypair:
        path: "{{ automation_home }}/.ssh/id_ed25519"
        type: ed25519
        owner: "{{ automation_user }}"
        group: "{{ automation_group }}"
        mode: '0600'
        comment: "{{ ssh_key_comment }}"
      register: ssh_keypair

    - name: Create authorized_keys file
      ansible.builtin.file:
        path: "{{ automation_home }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ automation_user }}"
        group: "{{ automation_group }}"
        mode: '0600'

    - name: Add public key to authorized_keys (self-authorization)
      ansible.posix.authorized_key:
        user: "{{ automation_user }}"
        key: "{{ ssh_keypair.public_key }}"
        comment: "{{ ssh_key_comment }}"
        state: present

    - name: Configure passwordless sudo for ansible user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "{{ automation_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'

    - name: Disable password login only for ansible user
      ansible.builtin.command: "passwd -l {{ automation_user }}"
...
