---
- name: Prepare Rocky 10 machine for Ansible automation
  hosts: "{{ target_host }}"
  become: yes

  vars_prompt:
    - name: "target_host"
      prompt: "Machine to set up
      private: no
    - name: "username"
      prompt: "User to SSH as (needs ROOT access)"
      private: no
      default: "root"
    - name: "password"
      prompt: "Password of initial user"
      private: yes
    - name: "ansible_username"
      prompt: "Ansible username"
      default: "ansible"


  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_become_pass: "{{ password }}"
    ansible_user: "{{ ansible_username }}"
    ansible_group: "{{ ansible_username }}"
    ansible_home: /home/ansible
    ssh_key_comment: "ansible-automation-key"

  tasks:
    - name: Create ansible group
      group:
        name: "{{ ansible_group }}"
        state: present

    - name: Create ansible user
      user:
        name: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        home: "{{ ansible_home }}"
        shell: /bin/bash
        create_home: yes
        system: no
        state: present

    - name: Set up SSH directory for ansible user
      file:
        path: "{{ ansible_home }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: '0700'

    - name: Generate SSH key pair for ansible user
      openssh_keypair:
        path: "{{ ansible_home }}/.ssh/id_ed25519"
        type: ed25519
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: '0600'
        comment: "{{ ssh_key_comment }}"
      register: ssh_keypair

    - name: Create authorized_keys file
      file:
        path: "{{ ansible_home }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: '0600'

    - name: Add public key to authorized_keys (self-authorization)
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ ssh_keypair.public_key }}"
        comment: "{{ ssh_key_comment }}"
        state: present

    - name: Configure passwordless sudo for ansible user
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'

    - name: Disable password login only for ansible user
      command: "passwd -l {{ ansible_user_name }}"
...
