---
collections:
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.general
    version: ">=1.0.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: community.docker
    version: ">=3.4.11"
  - name: community.mysql
    version: ">=3.0.0"
  - name: ansible.utils
...
