[Service]
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ReadWritePaths=/var/log/kea /var/lib/kea /run/kea /var/run/kea
PrivateDevices=true
MemoryDenyWriteExecute=true
