---
galaxy_info:
  author: Ctrl-Alt-GG
  description: Bracket deployment role using Docker Compose with deterministic secrets
  company: Ctrl-Alt-GG
  license: "All Rights Reserved"
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - bracket
    - docker
    - reverseproxy

dependencies: []

collections:
  - ansible.posix
  - community.general
  - community.docker
...
