---
- name: Restart tac_plus
  ansible.builtin.systemd:
    name: "{{ tacacs_service_name }}"
    state: restarted

- name: Restart auditd
  ansible.builtin.command: augenrules --load
  changed_when: false
...
